// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAB2hahOQ33iRuDjvNRDPFvszMF7Xt8n0',
    appId: '1:935425204716:web:c4247b13d1b64c40e120c9',
    messagingSenderId: '935425204716',
    projectId: 'timermeet',
    authDomain: 'timermeet.firebaseapp.com',
    databaseURL: 'https://timermeet-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'timermeet.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfCC9fVCMxEMtqLNeGggMi-MvmB3VaxzQ',
    appId: '1:935425204716:android:8948f34d992b089ce120c9',
    messagingSenderId: '935425204716',
    projectId: 'timermeet',
    databaseURL: 'https://timermeet-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'timermeet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaDQ9HqQslk1vpBNG54hfH3-U2yMhcrAI',
    appId: '1:935425204716:ios:a8c2a1c3afdcfa1be120c9',
    messagingSenderId: '935425204716',
    projectId: 'timermeet',
    databaseURL: 'https://timermeet-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'timermeet.appspot.com',
    androidClientId: '935425204716-baadhk1ajm3t5k9rp6hk6o02r5mope7u.apps.googleusercontent.com',
    iosClientId: '935425204716-4emc99g0iu8giblvgj2njtain7tmegsj.apps.googleusercontent.com',
    iosBundleId: 'com.example.timerMeet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaDQ9HqQslk1vpBNG54hfH3-U2yMhcrAI',
    appId: '1:935425204716:ios:a8c2a1c3afdcfa1be120c9',
    messagingSenderId: '935425204716',
    projectId: 'timermeet',
    databaseURL: 'https://timermeet-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'timermeet.appspot.com',
    androidClientId: '935425204716-baadhk1ajm3t5k9rp6hk6o02r5mope7u.apps.googleusercontent.com',
    iosClientId: '935425204716-4emc99g0iu8giblvgj2njtain7tmegsj.apps.googleusercontent.com',
    iosBundleId: 'com.example.timerMeet',
  );
}
